CREATE TABLE IF NOT EXISTS gateway_routes (
  id VARCHAR(100) PRIMARY KEY,
  path_pattern VARCHAR(255) NOT NULL,
  target_uri VARCHAR(500) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
